version: '3.5'

services:
  api:
    container_name: api_blindis
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app